Feat/init repo folder structure (#1)
* feat: project struct folders added

* feat: MIT License added

* feat: README.md added

* feat: health endpoint added

* fix: pr action directed to /health

* Update src/main/kotlin/com/rbbozkurt/openbankingapi/controller/HealthController.kt

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* fix: imports reordered

* fix: retry added to pr check action

* feat: health indicator added

* feat: health config added

* feat: conditional property added

* fix: data field set null

* Update src/main/kotlin/com/rbbozkurt/openbankingapi/service/health/implementation/PlaidHealthIndicator.kt

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Update src/main/kotlin/com/rbbozkurt/openbankingapi/service/health/implementation/PlaidSandboxHealthIndicator.kt

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -19,6 +19,16 @@ jobs:
         run: docker build -t openbanking-api:pr-test .
       - name: Run Docker Container (Smoke Test)
         run: |
-          docker run -d --rm -p 8080:8080 openbanking-api:pr-test
-          sleep 10
-          curl --fail http://localhost:8080 || (echo "❌ Health check failed" && exit 1)
+            CONTAINER_ID=$(docker run -d -p 8080:8080 openbanking-api:pr-test)
+            for i in {1..10}; do
+              if curl --fail http://localhost:8080/health; then
+                docker stop $CONTAINER_ID
+                exit 0
+              fi
+              sleep 2
+            done
+            docker logs $CONTAINER_ID
+            docker stop $CONTAINER_ID
+            echo "❌ Health check failed"
+            exit 1
+
